Login = "kedalat"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "Dissent-CS"
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 16
Simulation = "CoSimul"
Hosts = 0
Debug = 0
RunWait = 0
Suite = "Ed25519"
PreScript = ""
